from typing import Tuple, Dict

import src.share.models as m

STATE_DEFINITIONS: Dict[int, Tuple[m.MIGProfile, ...]] = {
    1: (m.MIGProfile.MIG_7G,),
    2: (
        m.MIGProfile.MIG_4G,
        m.MIGProfile.MIG_3G,
    ),
    3: (
        m.MIGProfile.MIG_4G,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_LARGE,
    ),
    4: (
        m.MIGProfile.MIG_4G,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_LARGE,
    ),
    8: (
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_3G,
    ),
    9: (
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_3G,
    ),
    10: (
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_3G,
    ),
    11: (
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_3G,
    ),
    12: (
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_LARGE,
    ),
    13: (
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_LARGE,
    ),
    14: (
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_LARGE,
    ),
    15: (
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_LARGE,
    ),
    16: (
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_LARGE,
    ),
    17: (
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_2G,
        m.MIGProfile.MIG_1G_LARGE,
    ),
    19: (
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_SMALL,
        m.MIGProfile.MIG_1G_LARGE,
    ),
}

STATE_ID_MAP = {sid: i for i, sid in enumerate(sorted(STATE_DEFINITIONS.keys()))}

SLICE_MAPPING = {
    1: [[0, 1, 2, 3, 4, 5, 6]],
    2: [[0, 1, 2, 3], [4, 5, 6]],
    3: [[0, 1, 2, 3], [4, 5], [6]],
    4: [[0, 1, 2, 3], [4], [5], [6]],
    8: [[0, 1], [2, 3], [4, 5, 6]],
    9: [[0, 1], [2], [3], [4, 5, 6]],
    10: [[0], [1], [2, 3], [4, 5, 6]],
    11: [[0], [1], [2], [3], [4, 5, 6]],
    12: [[0, 1], [2, 3], [4, 5], [6]],
    13: [[0, 1], [2], [3], [4, 5], [6]],
    14: [[0], [1], [2, 3], [4, 5], [6]],
    15: [[0, 1], [2], [3], [4], [5], [6]],
    16: [[0], [1], [2, 3], [4], [5], [6]],
    17: [[0], [1], [2], [3], [4, 5], [6]],
    19: [[0], [1], [2], [3], [4], [5], [6]],
}

TRANSITION_MATRIX = {
    (1, 2): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1],
        target_state_id=2,
    ),
    (1, 3): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2],
        target_state_id=3,
    ),
    (1, 4): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3],
        target_state_id=4,
    ),
    (1, 8): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2],
        target_state_id=8,
    ),
    (1, 9): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3],
        target_state_id=9,
    ),
    (1, 10): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3],
        target_state_id=10,
    ),
    (1, 11): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3, 4],
        target_state_id=11,
    ),
    (1, 12): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3],
        target_state_id=12,
    ),
    (1, 13): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3, 4],
        target_state_id=13,
    ),
    (1, 14): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3, 4],
        target_state_id=14,
    ),
    (1, 15): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3, 4, 5],
        target_state_id=15,
    ),
    (1, 16): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3, 4, 5],
        target_state_id=16,
    ),
    (1, 17): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3, 4, 5],
        target_state_id=17,
    ),
    (1, 19): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3, 4, 5, 6],
        target_state_id=19,
    ),
    (2, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[0],
        target_state_id=1,
    ),
    (2, 3): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[1],
        mig_target=[1, 2],
        target_state_id=3,
    ),
    (2, 4): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[1],
        mig_target=[1, 2, 3],
        target_state_id=4,
    ),
    (2, 8): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1],
        target_state_id=8,
    ),
    (2, 9): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2],
        target_state_id=9,
    ),
    (2, 10): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2],
        target_state_id=10,
    ),
    (2, 11): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3],
        target_state_id=11,
    ),
    (3, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2],
        mig_target=[0],
        target_state_id=1,
    ),
    (3, 2): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[1, 2],
        mig_target=[1],
        target_state_id=2,
    ),
    (3, 4): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[1],
        mig_target=[1, 2],
        target_state_id=4,
    ),
    (3, 12): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1],
        target_state_id=12,
    ),
    (3, 13): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2],
        target_state_id=13,
    ),
    (3, 14): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2],
        target_state_id=14,
    ),
    (3, 17): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3],
        target_state_id=17,
    ),
    (4, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3],
        mig_target=[0],
        target_state_id=1,
    ),
    (4, 2): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[1, 2, 3],
        mig_target=[1],
        target_state_id=2,
    ),
    (4, 3): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[1, 2],
        mig_target=[1],
        target_state_id=3,
    ),
    (4, 15): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2],
        target_state_id=15,
    ),
    (4, 16): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2],
        target_state_id=16,
    ),
    (4, 19): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1, 2, 3],
        target_state_id=19,
    ),
    (8, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2],
        mig_target=[0],
        target_state_id=1,
    ),
    (8, 2): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[0],
        target_state_id=2,
    ),
    (8, 9): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[1, 2],
        target_state_id=9,
    ),
    (8, 10): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1],
        target_state_id=10,
    ),
    (8, 12): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[2],
        mig_target=[0, 3],
        target_state_id=12,
    ),
    (9, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3],
        mig_target=[0],
        target_state_id=1,
    ),
    (9, 2): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2],
        mig_target=[0],
        target_state_id=2,
    ),
    (9, 8): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[1, 2],
        mig_target=[0],
        target_state_id=8,
    ),
    (9, 11): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1],
        target_state_id=11,
    ),
    (9, 13): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[3],
        mig_target=[0, 4],
        target_state_id=13,
    ),
    (9, 15): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[3],
        mig_target=[1, 2, 5],
        target_state_id=15,
    ),
    (10, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3],
        mig_target=[0],
        target_state_id=1,
    ),
    (10, 2): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2],
        mig_target=[0],
        target_state_id=2,
    ),
    (10, 8): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[0],
        target_state_id=8,
    ),
    (10, 11): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[2],
        mig_target=[0, 1],
        target_state_id=11,
    ),
    (10, 14): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[3],
        mig_target=[2, 4],
        target_state_id=14,
    ),
    (10, 16): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[3],
        mig_target=[0, 1, 5],
        target_state_id=16,
    ),
    (11, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3, 4],
        mig_target=[0],
        target_state_id=1,
    ),
    (11, 2): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3],
        mig_target=[0],
        target_state_id=2,
    ),
    (11, 9): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[0],
        target_state_id=9,
    ),
    (11, 10): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[2],
        target_state_id=10,
    ),
    (11, 17): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[4],
        mig_target=[4, 5],
        target_state_id=17,
    ),
    (11, 19): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[4],
        mig_target=[0, 1, 6],
        target_state_id=19,
    ),
    (12, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3],
        mig_target=[0],
        target_state_id=1,
    ),
    (12, 3): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[0],
        target_state_id=3,
    ),
    (12, 8): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 3],
        mig_target=[2],
        target_state_id=8,
    ),
    (12, 13): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[1, 2],
        target_state_id=13,
    ),
    (12, 14): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1],
        target_state_id=14,
    ),
    (13, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3, 4],
        mig_target=[0],
        target_state_id=1,
    ),
    (13, 3): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2],
        mig_target=[0],
        target_state_id=3,
    ),
    (13, 9): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 4],
        mig_target=[3],
        target_state_id=9,
    ),
    (13, 12): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[1, 2],
        mig_target=[0],
        target_state_id=12,
    ),
    (13, 15): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[1, 2],
        target_state_id=15,
    ),
    (13, 17): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1],
        target_state_id=17,
    ),
    (14, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3, 4],
        mig_target=[0],
        target_state_id=1,
    ),
    (14, 3): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2],
        mig_target=[0],
        target_state_id=3,
    ),
    (14, 10): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[2, 4],
        mig_target=[3],
        target_state_id=10,
    ),
    (14, 12): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[0],
        target_state_id=12,
    ),
    (14, 16): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[2],
        mig_target=[0, 1],
        target_state_id=16,
    ),
    (14, 17): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[2],
        mig_target=[0, 1],
        target_state_id=17,
    ),
    (15, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3, 4, 5],
        mig_target=[0],
        target_state_id=1,
    ),
    (15, 4): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2],
        mig_target=[0],
        target_state_id=4,
    ),
    (15, 9): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[1, 2, 5],
        mig_target=[3],
        target_state_id=9,
    ),
    (15, 13): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[1, 2],
        mig_target=[0],
        target_state_id=13,
    ),
    (15, 19): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[0],
        mig_target=[0, 1],
        target_state_id=19,
    ),
    (16, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3, 4, 5],
        mig_target=[0],
        target_state_id=1,
    ),
    (16, 4): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2],
        mig_target=[0],
        target_state_id=4,
    ),
    (16, 10): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 5],
        mig_target=[3],
        target_state_id=10,
    ),
    (16, 14): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[2],
        target_state_id=14,
    ),
    (16, 19): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[2],
        mig_target=[0, 1],
        target_state_id=19,
    ),
    (17, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3, 4, 5],
        mig_target=[0],
        target_state_id=1,
    ),
    (17, 3): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3],
        mig_target=[0],
        target_state_id=3,
    ),
    (17, 11): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[4, 5],
        mig_target=[4],
        target_state_id=11,
    ),
    (17, 13): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[0],
        target_state_id=13,
    ),
    (17, 14): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[2],
        target_state_id=14,
    ),
    (17, 19): m.Action(
        action=m.ActionType.SPLIT,
        gpu_id=-1,
        mig_src=[4],
        mig_target=[0, 1],
        target_state_id=19,
    ),
    (19, 1): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3, 4, 5, 6],
        mig_target=[0],
        target_state_id=1,
    ),
    (19, 4): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 2, 3],
        mig_target=[0],
        target_state_id=4,
    ),
    (19, 11): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1, 6],
        mig_target=[4],
        target_state_id=11,
    ),
    (19, 15): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[0],
        target_state_id=15,
    ),
    (19, 16): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[2],
        target_state_id=16,
    ),
    (19, 17): m.Action(
        action=m.ActionType.MERGE,
        gpu_id=-1,
        mig_src=[0, 1],
        mig_target=[4],
        target_state_id=17,
    ),
}
