services:
  vllm-server:
    image: vllm/vllm-openai:v0.17.0.custom
    tty: true
    runtime: nvidia
    shm_size: "10gb"
    ports:
      - "${HOST_PORT}:8000"
    environment:
      - MIG_UUID=${MIG_UUID}
      - NVIDIA_VISIBLE_DEVICES=${MIG_UUID}
      - HF_HOME=/root/.cache/huggingface
      - VLLM_CACHE_ROOT=/root/.cache/vllm
    volumes:
      - ~/.cache:/root/.cache
      - ./configs:/vllm-workspace/configs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${MIG_UUID}"]
              capabilities: [gpu, utility]
    command: --config /vllm-workspace/configs/${MODEL_FILENAME}.yaml
