training:
  phase: 1
  sb3_norm: true
  action-interval: 120.0 # seconds
  total_timesteps: 1024000
  arrival_rate_history_length: 5
  normalization:
    current_budget: 150.0
    total_sm_ratio: 7.0
    total_vram_ratio: 40.0
    mig_geometry: 7.0
    last_action: 5.0
    vram_transfer_amount: 20.0
    arrival_rate: 10.0
    avg_queue_length: 10.0
    avg_running_requests: 100.0
    avg_composite_latency: 5.0
    queue_length_trend_clamp: 3.0
    default_waiting_qj: 10.0
  PPO:
    episode_length: 1024
    n_steps: 256
    lr_max: 3.0e-4
    lr_min: 5.0e-5
    batch_size: 64
    n_epochs: 15
    gamma: 0.995
    gae_lambda: 0.90
    clip_range: 0.2
    ent_coef_schd: true
    ent_coef: 0.02
    min_ent_coef: 0.01
    max_ent_coef: 0.05
    net_arch:
      pi: [128, 128]
      vf: [512, 512]
  action_mask:
    split_merge_cooldown_steps: 10
  patterns:
    busy:
      duration: [2200.0, 2600.0]
      rate:
        CodingAgent: [2.0, 4.0]
        RAGAgent: [2.0, 4.0]
    idle:
      duration: [2200.0, 2600.0]
      rate:
        CodingAgent: [0.1, 0.5]
        RAGAgent: [0.1, 0.5]
    balanced:
      duration: [3800.0, 4200.0]
      rate:
        CodingAgent: [0.5, 1.5]
        RAGAgent: [0.5, 1.5]
  reconfig:
    budget: 150.0 # seconds
    refresh: 15.0 # minutes
  reward:
    # Reward function:
    # R_t = -\left( \sum_{k \in \text{Agents}} \left[ \frac{\alpha_k \cdot \overline{\Psi}(L_k)}{Q_k} \right] + \Omega(a_t) \right)
    # \overline{\Psi}(L_k) = \frac{1}{|\text{Req}_k| + \epsilon} \sum_{j \in \text{Req}_k} \left[ w_{T} \cdot \text{TTFT}_j + w_{P} \cdot \text{TPOT}_j \right]
    Q: # quality-incentive factor
      7g.40gb: 10.0
      4g.20gb: 3.0
      3g.20gb: 3.0
      2g.10gb: 1.0
      1g.10gb: 1.0
    alpha:
      CodingAgent: 1.1
      RAGAgent: 1.0
    w_ttft: 0.8 # weight in latency penalty
    w_tpot: 0.2 # weight in latency penalty
    gamma: 2.0 # reconfiguration penalty
    scaling: 0.1
    clipping: -30.0
    dynamic_penalty: true
