training:
  phase: 1
  action-interval: 120 # seconds
  reconfig:
    budget: 150 # seconds
    refresh: 15 # minutes
  reward:
    # Reward function:
    # R_t = -\left( \sum_{k \in \text{Agents}} \left[ \frac{\alpha_k \cdot \overline{\Psi}(L_k)}{Q_k} \right] + \Omega(a_t) \right)
    # \overline{\Psi}(L_k) = \frac{1}{|\text{Req}_k| + \epsilon} \sum_{j \in \text{Req}_k} \left[ w_{T} \cdot \text{TTFT}_j + w_{P} \cdot \text{TPOT}_j \right]
    Q: # quality-incentive factor
      7g.40gb: 2.0
      4g.20gb: 1.5
      3g.20gb: 1.5
      2g.10gb: 1.0
      1g.10gb: 1.0
    alpha:
      CodingAgent: 1.1
      RAGAgent: 1.0
    w_ttft: 0.8 # weight in latency penalty
    w_tpot: 0.2 # weight in latency penalty
    gamma: 0.3 # reconfiguration penalty
